name: date_calc
description: "Date Calculator."
publish_to: 'none' 
version: 2.0.1+2

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  japanese_date_converter: ^1.0.2 
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  math_expressions: ^3.0.0
  shared_preferences: ^2.5.3
  flutter_colorpicker: ^1.1.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  csv: ^6.0.0
  file_picker: ^8.0.6
  path_provider: ^2.1.3
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#F5F5F5"
  adaptive_icon_foreground: "assets/icon.png"